### ISSUE TITLE
ini bisa di ganti mas biar mengarah ke API kita yang udah ada di cloudinary

### ISSUE THREAD

**Issue by Subaruputra13** [Project-Capstone-Group-16/Golang_Kelompok-16#49]
https://github.com/Project-Capstone-Group-16/Golang_Kelompok-16/blob/57f4ef906082e9c80f349e699e7472c95e9a1038/utils/cloudinary.go#L13

**Comment by Subaruputra13** [comment]
cld, _ := cloudinary.NewFromURL(os.Getenv("CLD_URL")) <------- bisa di ganti seperti ini mas

**Comment by madhiemw** [comment]
done
